import type { EnhancedSignal, EnhancedBrandDetails } from '../types/enhanced';
import { createSignalId, createBrandId, createISODateString } from '../utils/typeUtils';

export const MOCK_SIGNALS: EnhancedSignal[] = [
  {
    id: createSignalId('1'),
    name: 'Market Trend Analysis',
    type: 'Analytics',
    status: 'active',
    createdAt: createISODateString('2024-01-15'),
    updatedAt: createISODateString('2024-01-20'),
    description: 'Comprehensive analysis of market trends and consumer behavior patterns.',
    tags: ['market', 'trends', 'analysis'],
    metadata: {
      source: 'market-data-api',
      confidence: 0.95,
      lastUpdated: createISODateString('2024-01-20'),
    },
  },
  {
    id: createSignalId('2'),
    name: 'Social Media Sentiment',
    type: 'Social',
    status: 'inactive',
    createdAt: createISODateString('2024-01-10'),
    updatedAt: createISODateString('2024-01-18'),
    description: 'Real-time sentiment analysis from social media platforms.',
    tags: ['social', 'sentiment', 'monitoring'],
    metadata: {
      platforms: ['twitter', 'facebook', 'instagram'],
      sentiment: 'positive',
      volume: 1250,
    },
  },
  {
    id: createSignalId('3'),
    name: 'Competitor Monitoring',
    type: 'Competitive',
    status: 'pending',
    createdAt: createISODateString('2024-01-12'),
    updatedAt: createISODateString('2024-01-19'),
    description: 'Automated monitoring of competitor activities and market positioning.',
    tags: ['competitor', 'monitoring', 'intelligence'],
    metadata: {
      competitors: ['competitor-a', 'competitor-b'],
      frequency: 'daily',
      alerts: true,
    },
  },
];

export const MOCK_BRANDS: EnhancedBrandDetails[] = [
  {
    id: createBrandId('brand-1'),
    name: 'TechCorp Solutions',
    description: 'A leading technology company specializing in innovative software solutions for businesses.',
    website: 'https://techcorp.com',
    industry: 'Technology',
    logo: '/logos/techcorp.png',
    foundedYear: 2015,
    employeeCount: 250,
    revenue: 50000000,
    socialMedia: {
      twitter: '@techcorp',
      linkedin: 'techcorp-solutions',
      facebook: 'techcorp.solutions',
    },
    createdAt: createISODateString('2024-01-01'),
    updatedAt: createISODateString('2024-01-20'),
  },
  {
    id: createBrandId('brand-2'),
    name: 'GreenEnergy Corp',
    description: 'Sustainable energy solutions provider focused on renewable technologies and environmental impact.',
    website: 'https://greenenergy.com',
    industry: 'Energy',
    logo: '/logos/greenenergy.png',
    foundedYear: 2018,
    employeeCount: 180,
    revenue: 35000000,
    socialMedia: {
      twitter: '@greenenergy',
      linkedin: 'greenenergy-corp',
      facebook: 'greenenergy.corp',
    },
    createdAt: createISODateString('2024-01-05'),
    updatedAt: createISODateString('2024-01-18'),
  },
  {
    id: createBrandId('brand-3'),
    name: 'HealthTech Innovations',
    description: 'Revolutionary healthcare technology company developing AI-powered medical solutions.',
    website: 'https://healthtech.com',
    industry: 'Healthcare',
    logo: '/logos/healthtech.png',
    foundedYear: 2020,
    employeeCount: 120,
    revenue: 25000000,
    socialMedia: {
      twitter: '@healthtech',
      linkedin: 'healthtech-innovations',
      facebook: 'healthtech.innovations',
    },
    createdAt: createISODateString('2024-01-10'),
    updatedAt: createISODateString('2024-01-15'),
  },
  {
    id: createBrandId('brand-4'),
    name: 'FinanceFlow Systems',
    description: 'Advanced financial technology platform providing comprehensive banking and investment solutions.',
    website: 'https://financeflow.com',
    industry: 'Financial Services',
    logo: '/logos/financeflow.png',
    foundedYear: 2017,
    employeeCount: 300,
    revenue: 75000000,
    socialMedia: {
      twitter: '@financeflow',
      linkedin: 'financeflow-systems',
      facebook: 'financeflow.systems',
    },
    createdAt: createISODateString('2024-01-08'),
    updatedAt: createISODateString('2024-01-22'),
  },
  {
    id: createBrandId('brand-5'),
    name: 'EduTech Academy',
    description: 'Online education platform offering interactive learning experiences and professional development courses.',
    website: 'https://edutech.com',
    industry: 'Education',
    logo: '/logos/edutech.png',
    foundedYear: 2019,
    employeeCount: 95,
    revenue: 18000000,
    socialMedia: {
      twitter: '@edutech',
      linkedin: 'edutech-academy',
      facebook: 'edutech.academy',
    },
    createdAt: createISODateString('2024-01-12'),
    updatedAt: createISODateString('2024-01-19'),
  },
];

// Keep the original export for backward compatibility
export const MOCK_BRAND_DETAILS: EnhancedBrandDetails = MOCK_BRANDS[0];
