// Export all utility functions from a single entry point
export * from './typeGuards';
export * from './typeUtils';

// String utilities
export {
  capitalize,
  toTitleCase,
  toKebabCase,
  toCamelCase,
  toSnakeCase,
  truncate,
  normalizeWhitespace,
  generateRandomString,
  isValidEmailString,
  isValidUrlString,
  getInitials,
  maskSensitive,
  slugify,
  pluralize,
  formatNumberSimple,
  formatCurrencySimple,
} from './stringUtils';

// Array utilities
export {
  unique,
  uniqueBy,
  groupBy,
  sortBy,
  chunk,
  flatten,
  intersection,
  difference,
  union,
  shuffle,
  randomItem,
  randomItems,
  moveItem,
  removeWhere,
  partition,
  sum,
  average,
  min,
  max,
  range,
  zip,
} from './arrayUtils';

// Object utilities
export {
  deepClone,
  deepMergeObjects,
  isObjectValue,
  get as getObjectProperty,
  set,
  omit,
  pick,
  hasAllKeys,
  hasAnyKey,
  invert,
  mapValues,
  mapKeys,
  filterObject,
  toPairs,
  fromPairs,
  objectSize,
  isEmpty,
  keyBy,
  groupByToObject,
} from './objectUtils';

// Validation utilities
export {
  isRequired,
  minLength,
  maxLength,
  inRange,
  isValidEmail,
  isValidUrl,
  matchesPattern,
  isOneOf,
  isNotOneOf,
  isAlphanumeric,
  isAlpha,
  isNumeric,
  isPositive,
  isNonNegative,
  isInteger,
  isFutureDate,
  isPastDate,
  isDateInRange,
  combineValidationResults,
  validateObject,
  createValidator,
} from './validationUtils';

// Date utilities
export {
  DATE_FORMATS,
  formatDate,
  parseDate,
  startOfDay,
  endOfDay,
  startOfWeek,
  endOfWeek,
  startOfMonth,
  endOfMonth,
  startOfYear,
  endOfYear,
  addDays,
  addMonths,
  addYears,
  differenceInDays,
  differenceInHours,
  differenceInMinutes,
  isToday,
  isYesterday,
  isTomorrow,
  isPast,
  isFuture,
  isWithinRange,
  getAge,
  getRelativeTime,
  getDaysInMonth,
  isLeapYear,
  getQuarter,
  getWeekNumber,
} from './dateUtils';

// Format utilities
export {
  formatNumber,
  formatCurrency,
  formatPercentage,
  formatDecimal,
  formatCompactNumber,
  formatFileSize,
  formatDuration,
  formatPhoneNumber,
  formatCreditCard,
  formatSSN,
  formatName,
  formatAddress,
  formatList,
  formatRange,
  formatDateRange,
  formatTimeRange,
  formatBoolean,
  formatWithUnit,
  formatWithPrefix,
  formatWithSuffix,
  formatWithPrefixAndSuffix,
  formatWithMask,
  formatWithPlaceholder,
} from './formatUtils';

// Storage utilities
export {
  localStorage,
  sessionStorage,
  cookies,
  IndexedDBStorage,
  StorageManager,
} from './storageUtils';

// API utilities
export {
  get,
  post,
  put,
  patch,
  del,
  makeRequest,
  ApiClient,
  EnhancedApiClient,
  ApiError,
  InterceptorManager,
} from './apiUtils';

// Performance utilities
export {
  debounce,
  throttle,
  memoize,
  PerformanceTimer,
  PerformanceObserverWrapper,
  LazyLoader,
  VirtualScroller,
  BatchProcessor,
  getMemoryUsage,
  FrameRateCounter,
} from './performanceUtils';

// DOM utilities
export {
  $,
  $$,
  createElement,
  addClass,
  removeClass,
  toggleClass,
  hasClass,
  setClasses,
  getComputedStyle,
  setStyle,
  getElementPosition,
  isInViewport,
  scrollIntoView,
  getScrollPosition,
  setScrollPosition,
  getElementDimensions,
  addEventListener,
  addDelegatedEventListener,
  waitForElement,
  cloneElement,
  removeElement,
  replaceElement,
  insertAfter,
  insertBefore,
  getClosest,
  getParents,
  getNextSibling,
  getPreviousSibling,
  getSiblings,
  isVisible,
  isHidden,
  focus,
  blur,
  selectAllText,
} from './domUtils';
